---
Name: deploynaut-environmentconfig
After:
  - '#deploynaut'
---
DNEnvironment:
  extensions:
    - 'EnvironmentConfig\EnvironmentExtension'
DNRoot:
  extensions:
    - 'EnvironmentConfig\Dispatcher'
  url_handlers:
    'project/$Project/environment/$Environment/configuration': 'configuration'
    'project/$Project/environment/$Environment/configuration_save': 'save'
