---
Name: deploynaut-environmentconfig
After:
  - '#deploynautroutes'
---
DNEnvironment:
  extensions:
    - 'EnvironmentConfig\EnvironmentExtension'
Director:
  rules:
    'naut/project/$Project/environment/$Environment/configuration': 'EnvironmentConfig\Dispatcher',
